ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_type_check;

ALTER TABLE notifications
    ADD CONSTRAINT notifications_type_check CHECK (type IN (
        'CASE_CREATED',
        'CASE_UPDATED',
        'CASE_STATUS_CHANGED',
        'CASE_CLOSED',
        'DOCUMENT_ADDED',
        'DEADLINE_CREATED',
        'DEADLINE_APPROACHING',
        'DEADLINE_OVERDUE',
        'DEADLINE_COMPLETED',
        'HEARING_CREATED',
        'HEARING_STATUS_CHANGED',
        'INVOICE_CREATED',
        'INVOICE_ISSUED',
        'PAYMENT_RECEIVED',
        'INVOICE_OVERDUE',
        'CONSULTATION_CREATED',
        'CONSULTATION_ASSIGNED',
        'CONSULTATION_ANSWERED',
        'CONSULTATION_CLOSED',
        'CONSULTATION_CANCELLED',
        'APPOINTMENT_CREATED',
        'APPOINTMENT_UPDATED',
        'APPOINTMENT_CANCELLED',
        'APPOINTMENT_REMINDER',
        'JUDICIAL_CASE_REGISTERED',
        'JUDICIAL_STATUS_CHANGED'
    ));