server:
  port: 9000

spring:
  application:
    name: legalflow-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://keycloak:8080/realms/legalflow/protocol/openid-connect/certs}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
